[17.06] Add cgroup namespaces
docker/runc pull request #6
Opened 2018-12-05 16:47 UTC by crosbymichael

Cherry pick of the upstream change to support cgroup namespaces and consistent process addition to cgroups.

2019-01-23 02:48 UTC, kolyshkin commented
Upstream commit https://github.com/opencontainers/runc/commit/df3fa115f97407713ec6ebe37a5ccf13b81dafd2 was backported with a bug; the hunk changing unshare() in libcontainer/nsenter/nsexec.c was applied incorrectly causing two `unshare()` calls instead of one. Second call fails, leading to EINVAL.

In addition, part of upstream commit https://github.com/opencontainers/runc/commit/e92add215 got mixed in here for some reason. Would be OK if it was complete I guess but it's not.

2019-01-23 02:51 UTC, kolyshkin commented on libcontainer/nsenter/nsexec.c
> +			pid_t child, first_child = -1;
adding `first_child` here is upstream commit e92add2151e50cd66c; I see some parts of that commit in here. I guess it either needs to be brought in (as a separate commit) or not (in this case `first_child` should not appear here).

2019-01-23 02:52 UTC, kolyshkin commented on libcontainer/nsenter/nsexec.c
> +						}
ditto (also possibly this ended up in the wrong place)

2019-01-23 02:54 UTC, kolyshkin commented on libcontainer/nsenter/nsexec.c
> +				bail("failed to unshare namespaces");
This hunk ended up in the wrong place. It should _replace_ a similar one, but without ` & ~CLONE_NEWCGROUP`.

2019-01-23 02:56 UTC, kolyshkin requested changes
need to fix a few things

2019-02-13 23:58 UTC, andrewhsu commented
Closing this PR now that #7 is in.

2019-02-13 23:58 UTC, closed without merging